version: '3.7'

services:
  main:
    container_name: auth
    build:
      context: .
      dockerfile: ../services/api-gateway/Dockerfile
    image: duretrip/api-gateway:latest
    restart: always
    ports:
      - 8006:8006
  
  jet:
    container_name: jet
    build:
      context: .
      dockerfile: ../services/jet/Dockerfile
    image: duretrip/jet:latest
    restart: always
    ports:
      - 8007:8007

      