apiVersion: apps/v1
kind: Deployment
metadata:
  name: jet-app
  labels:
    app: jet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jet-app
  template:
    metadata:
      labels:
        app: jet-app
    spec:
      containers:
        - name: jet-app
          image: duretrip/jet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8008
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "512Mi"
              cpu: "0.5"
          env:
            - name: DATABASE_TYPE
              value: postgres
            - name: DATABASE_NAME
              value: jet_db
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: chost

            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: port

            - name: JET_DATABASE_URL  # Setting Database name from configMap
              valueFrom :
                secretKeyRef :
                  name : jet-prisma-url
                  key :  url

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: username

            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password

            - name: RABBITMQ_CONECTION_URL
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_URL

            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_DEFAULT_USER
            
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS

              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_PASS

            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_USER

            - name: RABBITMQ_PASS
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_PASS

            - name: RABBITMQ_PAYMENT_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_PAYMENT_QUEUE
            
            - name: RABBITMQ_AUTH_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_AUTH_QUEUE

            - name: RABBITMQ_API_GATEWAY_QUEUE
              value: api-gateway-queue
            
            - name: RABBITMQ_HOTEL_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_HOTEL_QUEUE

            - name: RABBITMQ_JET_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_JET_QUEUE
            
            - name: AUTH_JWT_SECRET
              value: secret
            - name: AUTH_JWT_TOKEN_EXPIRES_IN
              value: '15'
            - name: AUTH_REFRESH_SECRET
              value: secret_for_refresh
            - name: AUTH_REFRESH_TOKEN_EXPIRES_IN
              value: 3650d
            - name: APP_PORT
              value: "8008"

---
apiVersion: v1
kind: Service
metadata:
  name: jet-svc
spec:
  selector:
    app: jet-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8008
      protocol: TCP
