apiVersion: apps/v1
kind: Deployment
metadata:
  name: maildev-deployment
  labels:
    app: maildev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maildev
  template:
    metadata:
      labels:
        app: maildev
    spec:
      containers:
      - name: maildev-container
        image: node:20.9.0-alpine
        command: ["sh", "-c"]
        args:
          - |
            npm i -g maildev@2.0.5
            maildev
        ports:
        - containerPort: 1080
        - containerPort: 1025

---
apiVersion: v1
kind: Service
metadata:
  name: maildev-service
  labels:
    app: maildev
spec:
  selector:
    app: maildev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1080
      # Optional: add a name to the port
      name: maildev-web
    - protocol: TCP
      port: 1025
      targetPort: 1025
      # Optional: add a name to the port
      name: maildev-smtp
  type: NodePort
