# apiVersion: rabbitmq.com/v1beta1
# kind: RabbitmqCluster
# metadata:
#  name: rabbitmqcluster-prod
# spec:
#  replicas: 1
#  resources:
#     requests:
#       cpu: 100m
#       memory: 128Mi
#     limits:
#       cpu: 500m
#       memory: 512Mi
#  rabbitmq:
#          additionalConfig: |
#                  log.console.level = info
#                  channel_max = 1700
#                  default_user_tags.administrator = true


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pv-claim
  labels:
    app: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          # resources:
          #   requests:
          #     memory: "256Mi" # Standard memory request
          #     cpu: "0.2"      # Standard CPU request
          #   limits:
          #     memory: "512Mi" # Standard memory limit
          #     cpu: "0.5"      # Standard CPU limit
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - name: rabbitmq-port-5672
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbitmq-port-15672
      protocol: TCP
      port: 80
      targetPort: 15672
