# apiVersion: v1
# kind: Namespace
# metadata:
#   name: test-rabbitmq
  
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: rabbitmq-admin
#   namespace: test-rabbitmq
# data:
#   user: user
#   pass: password

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: rabbitmq-admin
# data:
#   user: user
#   pass: password

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: erlang-cookie
#   namespace: test-rabbitmq
# data:
#   cookie: cFozNGdnaG5Tbjg3cmYxcXM=

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: rabbitmq-config
#   namespace: test-rabbitmq
# data:
#   enabled_plugins: |
#     [rabbitmq_peer_discovery_k8s, rabbitmq_management, rabbitmq_prometheus].
#   rabbitmq.conf: |
#     cluster_formation.peer_discovery_backend = k8s
#     cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
#     cluster_formation.k8s.address_type = hostname
#     cluster_formation.k8s.service_name = rabbitmq-service


#     queue_master_locator=min-masters


apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  # Define your environment variables here, e.g.:
  RABBITMQ_DEFAULT_USER: ${USERNAME}
  RABBITMQ_DEFAULT_PASS: ${PASSWORDE}
  RABBITMQ_USER: ${USERNAME}
  RABBITMQ_PASS: ${PASSWORDE}
  RABBITMQ_HOST: rabbitmq-service:5672
  RABBITMQ_URL: amqp://${USERNAME}:${PASSWORDE}@rabbitmq-service:5672
  RABBITMQ_AUTH_QUEUE: auth-queue
  RABBITMQ_PAYMENT_QUEUE: payment-queue
  RABBITMQ_HOTEL_QUEUE: hotel-queue
  RABBITMQ_JET_QUEUE: jet-queue
  RABBITMQ_API_GATEWAY_QUEUE: api-gateway-queue
  # Add other variables as needed